### ISSUE TITLE
Course 7 

### ISSUE THREAD

**Issue by cy2000yadav** [elmoallistair/google-data-analytics#2]
Hi,Thank you so much for your efforts in this course can you please upload Course 7 week 3,4,5 and course challenge answers please?

**Comment by elmoallistair** [comment]
Sure, i'm working on it

**Comment by cy2000yadav** [comment]
Thanks a lot for your reply

**Comment by elmoallistair** [comment]
Done, feel free to contribute!

**Comment by cy2000yadav** [comment]
Yes ,Thank you so much
